param(
    [string]$CollectPath = '',
    [string]$RunDir = '.\xinxin-run',
    [string]$RunIdPrefix = '',
    [string]$OutputPath = '',
    [string]$MarkdownOutputPath = '',
    [switch]$HumanReadable
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-SafeToken {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return ''
    }
    return ($Value -replace '[\\/:*?"<>|\s]+', '_')
}

function Get-SafeArray {
    param([object]$Value)
    if ($null -eq $Value) {
        return @()
    }
    if ($Value -is [string]) {
        return @($Value)
    }
    if ($Value -is [System.Collections.IEnumerable]) {
        return @($Value)
    }
    return @([string]$Value)
}

function Get-LatestCollectFile {
    param([string]$RunDirInput, [string]$Prefix)
    $rootDir = Resolve-Path $RunDirInput -ErrorAction SilentlyContinue
    if (-not $rootDir) {
        return $null
    }
    $qaDir = Join-Path $rootDir 'qa'
    if (-not (Test-Path $qaDir)) {
        $qaDir = $rootDir.Path
    }
    $files = Get-ChildItem -Path $qaDir -Recurse -File | Where-Object {
        $_.Name -like 'next-action-collect.json'
    }
    if ($files.Count -eq 0) {
        return $null
    }
    if (-not [string]::IsNullOrWhiteSpace($Prefix)) {
        $filtered = $files | Where-Object {
            ($_.FullName -like "*$Prefix*") -or ($_.DirectoryName -like "*$Prefix*")
        }
        if ($filtered.Count -gt 0) {
            $files = $filtered
        }
    }
    return ($files | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
}

function Add-PlanStep {
    param(
        [string]$Title,
        [string]$Priority,
        [string]$Reason,
        [string[]]$Commands,
        [string[]]$Playbooks,
        [string[]]$Notes
    )
    return [ordered]@{
        title = $Title
        priority = $Priority
        reason = $Reason
        commands = $Commands
        playbooks = $Playbooks
        notes = $Notes
    }
}

function New-NextStepCommand {
    param([string]$Line, [string]$Prefix)
    $safePrefix = Get-SafeToken $Prefix
    $prefixText = if ([string]::IsNullOrWhiteSpace($safePrefix)) { '' } else { " -RunIdPrefix $safePrefix" }
    return "powershell -ExecutionPolicy Bypass -File .\scripts\run-xinxin-v2.1-release-line.ps1 -Line $Line -NoFail$prefixText"
}

function Write-MarkdownReport {
    param([psobject]$Plan, [string]$OutputPath)
    $lines = @()
    $lines += '# Xinxin Remediation Plan'
    $lines += ''
    $lines += "| Field | Value |"
    $lines += "| --- | --- |"
    $lines += "| run_dir | $($Plan.run_dir) |"
    $lines += "| run_id_prefix | $($Plan.run_id_prefix) |"
    $lines += "| collect_path | $($Plan.collect_path) |"
    $lines += "| health_status | $($Plan.health_status) |"
    $lines += "| health_score | $($Plan.health_score) |"
    $lines += "| needs_attention | $($Plan.needs_attention) |"
    $lines += "| validation_hint | $($Plan.validation_hint) |"
    $lines += "| health_gate_blocked | $($Plan.health_gate_blocked) |"
    $lines += "| next_action_step | $($Plan.next_action_step) |"
    $lines += "| next_action_reason | $($Plan.next_action_reason) |"
    $lines += "| next_action_command | $($Plan.next_action_command) |"
    $lines += ''
    $lines += '## health_gate_reasons'
    if ($Plan.health_gate_reasons -and $Plan.health_gate_reasons.Count -gt 0) {
        foreach ($reason in $Plan.health_gate_reasons) {
            $lines += "- $reason"
        }
    } else {
        $lines += '- (none)'
    }

    $lines += ''
    $lines += '## remediation_plan'
    if ($Plan.remediation_plan -and $Plan.remediation_plan.Count -gt 0) {
        $idx = 1
        foreach ($step in $Plan.remediation_plan) {
            $lines += "### Step $idx - $($step.title)"
            $lines += "- priority: $($step.priority)"
            $lines += "- reason: $($step.reason)"
            if ($step.playbooks -and $step.playbooks.Count -gt 0) {
                $lines += '- playbooks:'
                foreach ($book in $step.playbooks) {
                    $lines += "  - $book"
                }
            }
            if ($step.notes -and $step.notes.Count -gt 0) {
                $lines += '- notes:'
                foreach ($note in $step.notes) {
                    $lines += "  - $note"
                }
            }
            if ($step.commands -and $step.commands.Count -gt 0) {
                $lines += '- commands:'
                $lines += '  ```powershell'
                foreach ($command in $step.commands) {
                    $lines += "  $command"
                }
                $lines += '  ```'
            }
            $lines += ''
            $idx++
        }
    } else {
        $lines += '- (none)'
    }
    $lines += ''
    $lines += '> Output generated by infer-xinxin-remediation-plan.ps1'
    Set-Content -Path $OutputPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
}

$safeRunIdPrefix = Get-SafeToken $RunIdPrefix

if ([string]::IsNullOrWhiteSpace($CollectPath)) {
    $CollectPath = Get-LatestCollectFile -RunDirInput $RunDir -Prefix $safeRunIdPrefix
}

if (-not $CollectPath) {
    throw "collect output not found. Set -CollectPath or run collect-xinxin-next-artifacts.ps1 first."
}

$collectSummary = Get-Content -Raw $CollectPath | ConvertFrom-Json
if (-not $collectSummary) {
    throw "failed to parse collect output: $CollectPath"
}

$healthGate = if ($collectSummary.health_gate) { $collectSummary.health_gate } else { @{} }
if (-not ($healthGate.enabled)) { $healthGate.enabled = @{fail_on_attention = $false; fail_on_critical = $false; min_health_score = 0 } }
if (-not ($healthGate.blocked -is [bool])) { $healthGate.blocked = $false }
if (-not ($healthGate.PSObject.Properties.Name -contains 'reasons')) { $healthGate.reasons = @() }

$nextAction = if ($collectSummary.next_action) { $collectSummary.next_action } else { @{ } }
$nextActionCommands = Get-SafeArray $nextAction.recommended_commands
$nextActionPlaybooks = Get-SafeArray $nextAction.recommended_playbooks
$nextActionNotes = Get-SafeArray $nextAction.recommended_notes
$nextActionPriority = if ($nextAction.recommended_priority) { $nextAction.recommended_priority } else { 'normal' }
$nextActionStep = if ($nextAction.recommended_step) { $nextAction.recommended_step } else { 'unknown' }
$nextActionReason = if ($nextAction.reason) { $nextAction.reason } else { if ($collectSummary.next_action_reason) { $collectSummary.next_action_reason } else { 'missing next-action' } }
$nextActionLine = if ($nextAction.recommended_line) { $nextAction.recommended_line } else { 'all' }

$plan = [ordered]@{
    timestamp = Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz'
    run_dir = if ($collectSummary.run_dir) { $collectSummary.run_dir } else { $RunDir }
    run_id_prefix = if (-not [string]::IsNullOrWhiteSpace($collectSummary.run_id_prefix)) { $collectSummary.run_id_prefix } elseif (-not [string]::IsNullOrWhiteSpace($safeRunIdPrefix)) { $safeRunIdPrefix } else { $null }
    collect_path = $CollectPath
    health_status = if ($collectSummary.health_status) { $collectSummary.health_status } else { 'unknown' }
    health_score = if ($null -ne $collectSummary.health_score) { [int]$collectSummary.health_score } else { 0 }
    needs_attention = if ($null -ne $collectSummary.needs_attention) { [bool]$collectSummary.needs_attention } else { $false }
    health_reasons = Get-SafeArray $collectSummary.health_reasons
    health_gate_enabled = $healthGate.enabled
    health_gate_blocked = $healthGate.blocked
    health_gate_reasons = Get-SafeArray $healthGate.reasons
    next_action_step = $nextActionStep
    next_action_reason = $nextActionReason
    next_action_command = if ($nextAction.recommended_command) { $nextAction.recommended_command } else { '' }
    remediation_plan = @()
    validation_hint = 'ok'
    playbooks = @('.\xinxin-run\qa\v2.1-failure-remediation-playbook.md', '.\xinxin-run\qa\v2.1-qa-checklist.md')
}

if ($nextActionCommands.Count -gt 0) {
    $plan.remediation_plan += Add-PlanStep -Title 'execute next_action_recommended_command' -Priority $nextActionPriority -Reason $nextActionReason -Commands $nextActionCommands -Playbooks $nextActionPlaybooks -Notes $nextActionNotes
}

if ($nextActionCommands.Count -eq 0 -and $nextActionStep -ne 'passed') {
    if ($healthGate.blocked) {
        $command = New-NextStepCommand -Line $nextActionLine -Prefix $safeRunIdPrefix
        $plan.remediation_plan += Add-PlanStep -Title 'run recovery line from health gate' -Priority 'high' -Reason 'health gate indicates blocked status' -Commands @($command) -Playbooks $plan.playbooks -Notes @('Run without gating first to allow diagnostic recovery file outputs.')
    } elseif ($collectSummary.health_reasons -and (Get-SafeArray $collectSummary.health_reasons).Count -gt 0) {
        $command = New-NextStepCommand -Line all -Prefix $safeRunIdPrefix
        $plan.remediation_plan += Add-PlanStep -Title 'full recovery rerun' -Priority 'medium' -Reason 'health snapshot indicates non-blocking warning' -Commands @($command) -Playbooks $plan.playbooks -Notes @('No hard block, but snapshot score below ideal. Keep change scope minimal.')
    } else {
        $command = New-NextStepCommand -Line all -Prefix $safeRunIdPrefix
        $plan.remediation_plan += Add-PlanStep -Title 'baseline recovery' -Priority 'low' -Reason 'prepare a clean rerun for consistency' -Commands @($command) -Playbooks $plan.playbooks -Notes @('Run baseline recovery and keep manual changes stable.')
    }
}

if ($healthGate.blocked) {
    $plan.validation_hint = 'health_gate_blocked'
} elseif ($collectSummary.health_status -eq 'critical' -or ($collectSummary.health_status -eq 'warning')) {
    $plan.validation_hint = "health_status_$($collectSummary.health_status)"
} elseif ($collectSummary.health_score -lt 70) {
    $plan.validation_hint = "health_score_below_70"
}

if ($OutputPath) {
    $plan | ConvertTo-Json -Depth 20 | Set-Content -Path $OutputPath -Encoding UTF8
}
if ($MarkdownOutputPath) {
    Write-MarkdownReport -Plan $plan -OutputPath $MarkdownOutputPath
}

$planJson = $plan | ConvertTo-Json -Depth 20

if ($HumanReadable) {
    Write-Host 'xinxin remediation plan'
    Write-Host ("collect_path: {0}" -f $CollectPath)
    Write-Host ("status: {0}, score: {1}, needs_attention: {2}" -f $plan.health_status, $plan.health_score, $plan.needs_attention)
    Write-Host ("health_gate_blocked: {0}" -f $plan.health_gate_blocked)
    Write-Host ("next_action_step: {0}" -f $plan.next_action_step)
    Write-Host ("validation_hint: {0}" -f $plan.validation_hint)
    Write-Host 'recommended plans:'
    if ($plan.remediation_plan.Count -gt 0) {
        foreach ($step in $plan.remediation_plan) {
            Write-Host ("- {0} [{1}] {2}" -f $step.title, $step.priority, $step.reason)
            foreach ($cmd in $step.commands) {
                Write-Host ("  - {0}" -f $cmd)
            }
        }
    } else {
        Write-Host '- (none)'
    }
}

Write-Output $planJson
